### ISSUE TITLE
Update node dependency to node 20

### ISSUE THREAD

**Issue by jonashogstrom** [dlemstra/code-sign-action#18]
Currently this action uses the deprecated node version 16, and that generates some warnings when using the action:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dlemstra/code-sign-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

Switching to node 20 was straight forward, but I can't figure out how to make a PR since my own fork is originally a fork from another fork... The code to fix this is available here (three lines modified in yaml-files): 

https://github.com/jonashogstrom/code-sign-action/commit/7aae9b81da7d565801f977b62eea0b2b3542ea92

A patched action version is available as jonashogstrom/code-sign-action@v2.0.11

**Comment by dlemstra** [comment]
Thanks for coming here and reporting this. I have updated v1 to use node20 instead.
