### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by ghstahl** [dlemstra/code-sign-action#3]
I have used vcsjones/AzureSignTool to successfully sign using keyvault.  

I then downloaded the same keyvault cert as a pfx, base64 encoded it and sent it to this action. 

Run dlemstra/code-sign-action@v1
  with:
    certificate: ***
    folder: windows-native-signing\x64\Release
    recursive: true
  env:
    AZURE_HTTP_USER_AGENT: 
    P7IdentityServer4SelfSigned-b64pfx: ***
Writing 2648 bytes to C:\Users\RUNNER~1\AppData\Local\Temp\certificate.pfx.
Signing windows-native-signing\x64\Release/hello.utls.dll.

SignTool Error: No certificates were found that met all the given criteria.

Is there an example of creating a pfx that works.  Also what about password protected pfx's?

BTW: I get the same No certificates were found that met all the given criteria.
when I generated my own certs using the following [blog](https://www.petri.com/create-self-signed-certificate-using-powershell).  I passed in the password when calling signtool.exe.

**Comment by dlemstra** [comment]
At this moment you will need to have a base64 encoded certificate that does not have a password. But I should probably extend this action to also allow a PFX file with a password. 

This project uses a base64 encoded PFX in the build pipeline but I should probably change this to use one that is created on the spot. But I think signtool needs to have the parent certificate in the store to make this work. And that is propably also why you are getting this error message. Not sure yet how we could make sure that the parent certificate is in the certificate store. Also not sure if this should be changed. What is your use case that you need a self signed certificate?

For myself for future reference: https://stackoverflow.com/questions/47547387/self-signed-code-signing-certificate-for-excel-add-in

**Comment by ghstahl** [comment]
Thanks.  On a side note, if AzureSignTool can sign a binary without having anything installed in the store, then neither should signtool.exe.  After all these years why does signtool.exe still have this requirement?  Too bad that it isn't open source so that it can get attention.  I would think that maybe having AzureSignTool take up a requirement to use a pfx would be better moving forward.

**Comment by dlemstra** [comment]
A password option has just been added.
