### ISSUE TITLE
SignTool Error: An error occurred while attempting to load the signing

### ISSUE THREAD

**Issue by Snazzie** [dlemstra/code-sign-action#5]
Run dlemstra/code-sign-action@v1
Writing 930 bytes to C:\Users\RUNNER~1\AppData\Local\Temp\certificate.pfx.
Signtool location is C:/Program Files (x86)/Windows Kits/10/bin/10.0.22000.0/x86/signtool.exe.
Signing ./Source/ClientApp/src-tauri/target/release/bundle/msi/Vital Utilities_0.0.24_x64.msi.

SignTool Error: An error occurred while attempting to load the signing

	certificate from: C:\Users\RUNNER~1\AppData\Local\Temp\certificate.pfx

**Comment by dlemstra** [comment]
What kind of certificate is this? Is the whole certificate chain trusted? This won't work with a self signed certificate.

**Comment by snapstreamjoe** [comment]
@Snazzie You are most likely having an issue because of the space in your file name. I have a PR out there to resolve that issue @dlemstra https://github.com/dlemstra/code-sign-action/pull/6

**Comment by Snazzie** [comment]
> @Snazzie You are most likely having an issue because of the space in your file name. I have a PR out there to resolve that issue @dlemstra #6

🤞

**Comment by snapstreamjoe** [comment]
@Snazzie The code has been released, please retry your test.
