### ISSUE TITLE
Certificate Password setting is a bit confusing

### ISSUE THREAD

**Issue by Lindsay-Mathieson** [dlemstra/code-sign-action#9]
First off, thanks for the amazing action, so easy to setup and worked first time for me. So much easier than the clutzy batch files I had setup for our inhouse build.

One thing that had me head scratching for a bit was this section in your docs:

`password: '${{ secrets.CERTIFICATE_PATH }}'`

I was trying to figure how a path was used before it clicked that it was meant to be the password, maybe a typo?

`password: '${{ secrets.CERTIFICATE_PASSWORD }}'`

would make more sense, 

thanks.

**Comment by dlemstra** [comment]
Good catch. It should be this instead: `password: '${{ secrets.CERTIFICATE_PASSWORD }}'`. Feel free to open a pull request to resolve this.

**Comment by Lindsay-Mathieson** [comment]
Would love to but I don't have permissions

**Comment by dlemstra** [comment]
You should be able to? You should first create a fork of this repository (https://docs.github.com/en/get-started/quickstart/fork-a-repo). And then you can open a pull request after you made your changes (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by dlemstra** [comment]
Thanks for helping out to fix this.
